name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install flake8 flake8-import-order flake8-future-import flake8-commas flake8-logging-format
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install test dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
    - name: Run unit tests
      run: python -m unittest
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install test dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
    - name: Run integration tests
      run: python .test.py
